2021-05-18T11:17:29.252733000Z -- Attaching packages --------------------------------------- tidyverse 1.3.0 --
2021-05-18T11:17:29.262212200Z v ggplot2 3.3.2     v purrr   0.3.4
2021-05-18T11:17:29.262234600Z v tibble  3.0.3     v dplyr   1.0.2
2021-05-18T11:17:29.262243200Z v tidyr   1.1.2     v stringr 1.4.0
2021-05-18T11:17:29.262250200Z v readr   1.3.1     v forcats 0.5.0
2021-05-18T11:17:29.429200200Z -- Conflicts ------------------------------------------ tidyverse_conflicts() --
2021-05-18T11:17:29.429219600Z x dplyr::filter() masks stats::filter()
2021-05-18T11:17:29.429227800Z x dplyr::lag()    masks stats::lag()
2021-05-18T11:17:29.444071500Z 
2021-05-18T11:17:29.444089900Z Attaching package: 'lubridate'
2021-05-18T11:17:29.444097600Z 
2021-05-18T11:17:29.445560400Z The following objects are masked from 'package:base':
2021-05-18T11:17:29.445576800Z 
2021-05-18T11:17:29.445584000Z     date, intersect, setdiff, union
2021-05-18T11:17:29.445590900Z 
2021-05-18T11:17:31.510211200Z Error in gzfile(file, "rb") : cannot open the connection
2021-05-18T11:17:31.510268700Z Calls: read_rds -> readRDS -> gzfile
2021-05-18T11:17:31.510277600Z In addition: Warning message:
2021-05-18T11:17:31.510284900Z In gzfile(file, "rb") :
2021-05-18T11:17:31.510291900Z   cannot open compressed file '/workspace/output/data/data_all.rds', probable reason 'No such file or directory'
2021-05-18T11:17:31.531492400Z Backtrace:
2021-05-18T11:17:31.531515500Z 1: gzfile(file, "rb")
2021-05-18T11:17:31.531706800Z 2: readRDS(path)
2021-05-18T11:17:31.531723700Z 3: read_rds(here::here("output", "data", "data_all.rds"))


state: failed
commit: ad2632c72fd11f4a1bf84fde807fe6b34f084c6b
docker_image_id: sha256:fd70d515514910d8399e807135f3decedae0a426b222b3488810a7aa5283eafb
exit_code: 1
job_id: eesveglgxolwomle
run_by_user: wjchulme
created_at: 2021-05-18T11:14:24Z
started_at: 2021-05-18T11:17:26Z
completed_at: 2021-05-18T11:17:34Z

Job exited with an error code

outputs:
  (no outputs)